image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: gitlab-ci
  CONTAINER_IMAGE: ${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA}
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

stages:
  - pre-build
  - build
  - package
  - deploy

hello:
  stage: pre-build
  script: "printenv"

maven-build:
  image: $CI_REGISTRY_IMAGE/build/maven-sync:latest
  stage: build
  cache:
    paths:
      - .m2/repository
  script: "mvn ${MAVEN_OPTS} package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE/$CONTAINER_IMAGE .
  - docker push $CI_REGISTRY_IMAGE/$CONTAINER_IMAGE

k8s-deploy:
  stage: deploy
  image: asorour/docker-aws-cli
  services:
      - docker:dind
  variables:
      DOCKER_DRIVER: overlay2
      HELM_EXPERIMENTAL_OCI: 1
  script:
    - apk add --no-cache \
        python3 \
        py3-pip \
        && pip3 install --upgrade pip \
        && pip3 install \
        awscli \
        && rm -rf /var/cache/apk/*
    - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $cluster_name
    - kubectl config use-context default
    - curl -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.3/docs/install/iam_policy.json
    - POLICY=$(aws iam create-policy \
      --policy-name AWSLoadBalancerControllerIAMPolicy \
      --policy-document file://iam_policy.json)
    - eksctl create iamserviceaccount \
      --cluster=<my-cluster> \
      --namespace=kube-system \
      --name=cluster-autoscaler \
      --attach-policy-arn=arn:aws:iam::${AWS_ID}:policy/${POLICY} \
      --override-existing-serviceaccounts \
      --approve
    - kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
    - helm repo add eks https://aws.github.io/eks-charts
    - helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
      --set clusterName=$cluster_name \
      --set serviceAccount.create=false \
      --set serviceAccount.name=aws-load-balancer-controller \
      -n kube-system
    - helm upgrade hello-aws ./ --install --set image.tag=${CI_COMMIT_SHORT_SHA}
    - 
build-docker-image:
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: build
  image: "docker:latest"
  cache:
    paths:
      - .m2/repository

  script:
    - wget -O Dockerfile ${CI_PROJECT_URL}/raw/${CI_COMMIT_BRANCH}/maven-dep-dockerfile
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/build/maven-sync:latest .
    - docker push $CI_REGISTRY_IMAGE/build/maven-sync:latest
  when: manual
