image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  CONTAINER_IMAGE: calleum/hello-aws:${CI_COMMIT_SHORT_SHA}

stages:
  - build
  - package
  - deploy

maven-build:
  image: $CI_REGISTRY_IMAGE/build/maven-sync:latest
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
  - docker build -t registry.gitlab.com/${CONTAINER_IMAGE} .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/${CONTAINER_IMAGE}

k8s-deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - helm upgrade hello-aws ./ --install --set image.tag=${CI_COMMIT_SHORT_SHA}

build-docker-image:
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: build
  image: "docker:latest"
  script:
    - wget -O Dockerfile https://gitlab.com/calleum/hello-aws/-/raw/master/maven-dep-dockerfile
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/build/maven-sync:latest .
    - docker push $CI_REGISTRY_IMAGE/build/maven-sync:latest
  when: manual
