apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-aws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-aws
  template:
    metadata:
      labels:
        app: hello-aws
    spec:
      containers:
        - name: hello-aws
          image: registry.gitlab.com/calleum/hello-aws:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: registry-credentials-kube
---

kind: Service
apiVersion: v1
metadata:
  name: hello-aws-service
spec:
  selector:
    app: hello-aws
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: NodePort
