apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsK
ICAgICAgICAgICAgInVzZXJuYW1lIjoiY3BlY3ExIiwKICAgICAgICAgICAgInBhc3N3b3JkIjoi
bmF2aU5hdmkxNDMiLAogICAgICAgICAgICAiZW1haWwiOiJjYWxsZXVtLnBlY3F1ZXV4QGdtYWls
LmNvbSIsCiAgICAgICAgICAgICJhdXRoIjoiZTJOd1pXTnhNWDA2ZTI1aGRtbE9ZWFpwTVRRemZR
PT0iCiAgICAJfQogICAgfQp9Cg==
